<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Acorn.Fbx</RootNamespace>
    <AssemblyName>Acorn.Fbx</AssemblyName>
    <Version>0.0.0</Version>
    <Authors>nyar-vm</Authors>
    <Description>Acorn FBX 格式库，提供 Autodesk FBX 模型/动画文件的扫描、编码和解码功能</Description>
    <PackageProjectUrl>https://github.com/nyar-vm/Acorn.cs</PackageProjectUrl>
    <RepositoryUrl>https://github.com/nyar-vm/Acorn.cs</RepositoryUrl>
    <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Acorn\Acorn.csproj" />
    <ProjectReference Include="..\Generator.Acorn\Generator.Acorn.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
