<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Acorn.Zip</RootNamespace>
    <AssemblyName>Acorn.Zip</AssemblyName>
    <Version>0.0.0</Version>
    <Authors>nyar-vm</Authors>
    <Description>Acorn ZIP 格式库，提供 ZIP 压缩包的扫描、解码和编码功能</Description>
    <PackageProjectUrl>https://github.com/nyar-vm/Acorn.cs</PackageProjectUrl>
    <RepositoryUrl>https://github.com/nyar-vm/Acorn.cs</RepositoryUrl>
    <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Acorn\Acorn.csproj" />
    <ProjectReference Include="..\Generator.Acorn\Generator.Acorn.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Readme.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>