<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Acorn.Native.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="xunit" Version="2.9.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\projects\Acorn\Acorn.csproj" />
    <ProjectReference Include="..\..\projects\Acorn.Elf\ELF.csproj" />
    <ProjectReference Include="..\..\projects\Acorn.Pe\Acorn.PE.csproj" />
    <ProjectReference Include="..\..\projects\Acorn.MachO\Acorn.MachO.csproj" />
    <ProjectReference Include="..\..\projects\Acorn.Nyar\Acorn.Nyar.csproj" />
  </ItemGroup>

</Project>
