<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <RootNamespace>Acorn.Clr</RootNamespace>
        <AssemblyName>Acorn.Clr</AssemblyName>
        <PackageId>Acorn.Clr</PackageId>
        <Version>0.0.0</Version>
        <Authors>Nyar Team - Acorn Group</Authors>
        <Description>Acorn CLR 格式编解码器，提供 .NET 程序集元数据和 MSIL 指令的解析与生成</Description>
        <PackageProjectUrl>https://github.com/nyar-vm/Acorn.cs</PackageProjectUrl>
        <RepositoryUrl>https://github.com/nyar-vm/Acorn.cs</RepositoryUrl>
        <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
        <PackageTags>acorn;clr;msil;metadata;assembly;dotnet</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Acorn\Acorn.csproj"/>
        <ProjectReference Include="..\Acorn.Pe\Acorn.PE.csproj"/>
    </ItemGroup>

</Project>
