<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Acorn.Office</RootNamespace>
    <AssemblyName>Acorn.Office</AssemblyName>
    <Version>0.0.0</Version>
    <Authors>nyar-vm</Authors>
    <Description>Acorn Office 格式库，提供 Office 97-2003 格式（.xls, .doc, .ppt）的扫描、编码和解码功能</Description>
    <PackageProjectUrl>https://github.com/nyar-vm/Acorn.cs</PackageProjectUrl>
    <RepositoryUrl>https://github.com/nyar-vm/Acorn.cs</RepositoryUrl>
    <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Acorn\Acorn.csproj" />
    <ProjectReference Include="..\Generator.Acorn\Generator.Acorn.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    <ProjectReference Include="..\Acorn.Zip\Acorn.Zip.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
